version: '3'
services:
  powertag:
    container_name: powertag2mqtt
    build: .
    #restart: unless-stopped
    privileged: true
    devices:
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220811170007-if00:/dev/ttyACM0
    volumes:
      - ./appdata:/var/lib/appdata
